# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VivaRealChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VivaRealChallenge
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 4.0'
  pod 'RealmSwift', '2.6.0'
  pod "Hero"
  pod 'FCAlertView'

  target 'VivaRealChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
